src/Entity/Order.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\UuidInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Order
 * @package App\Entity
 * @ORM\Entity
 * @ORM\Table(name="orders")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid")
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    private UuidInterface $id;

    /**
     * @ORM\Column
     */
    private string $state = "created";

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private \DateTimeImmutable $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?\DateTimeImmutable $canceledAt = null;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?\DateTimeImmutable $refusedAt = null;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?\DateTimeImmutable $acceptedAt = null;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?\DateTimeImmutable $settledAt = null;

    /**
     * @ORM\ManyToOne(targetEntity="Customer")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private Customer $customer;

    /**
     * @ORM\OneToMany(targetEntity="OrderLine", mappedBy="order", cascade={"persist"})
     */
    private Collection $lines;

    /**
     * @ORM\ManyToOne(targetEntity="Farm")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private Farm $farm;

    /**
     * @ORM\OneToMany(targetEntity="Slot", mappedBy="order", cascade={"persist"}, orphanRemoval=true)
     * @Assert\Count(min=1)
     */
    private Collection $slots;

    /**
     * @var Slot|null
     * @ORM\OneToOne(targetEntity="Slot")
     */
    private ?Slot $chosenSlot;

    /**
     * Order constructor.
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->lines = new ArrayCollection();
        $this->slots = new ArrayCollection();
    }

    /**
     * @return UuidInterface
     */
    public function getId(): UuidInterface
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getState(): string
    {
        return $this->state;
    }

    /**
     * @param string $state
     */
    public function setState(string $state): void
    {
        $this->state = $state;
    }

    /**
     * @return \DateTimeImmutable
     */
    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTimeImmutable $createdAt
     */
    public function setCreatedAt(\DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return Customer
     */
    public function getCustomer(): Customer
    {
        return $this->customer;
    }

    /**
     * @param Customer $customer
     */
    public function setCustomer(Customer $customer): void
    {
        $this->customer = $customer;
    }

    /**
     * @return ArrayCollection|Collection
     */
    public function getLines()
    {
        return $this->lines;
    }

    /**
     * @return int
     */
    public function getNumberOfProducts(): int
    {
        return array_sum($this->lines->map(fn (OrderLine $line) => $line->getQuantity())->toArray());
    }

    /**
     * @return float
     */
    public function getTotalIncludingTaxes(): float
    {
        return array_sum($this->lines->map(fn (OrderLine $line) => $line->getPriceIncludingTaxes())->toArray());
    }

    /**
     * @return \DateTimeImmutable|null
     */
    public function getCanceledAt(): ?\DateTimeImmutable
    {
        return $this->canceledAt;
    }

    /**
     * @param \DateTimeImmutable|null $canceledAt
     */
    public function setCanceledAt(?\DateTimeImmutable $canceledAt): void
    {
        $this->canceledAt = $canceledAt;
    }

    /**
     * @return \DateTimeImmutable|null
     */
    public function getRefusedAt(): ?\DateTimeImmutable
    {
        return $this->refusedAt;
    }

    /**
     * @param \DateTimeImmutable|null $refusedAt
     */
    public function setRefusedAt(?\DateTimeImmutable $refusedAt): void
    {
        $this->refusedAt = $refusedAt;
    }

    /**
     * @return Farm
     */
    public function getFarm(): Farm
    {
        return $this->farm;
    }

    /**
     * @param Farm $farm
     */
    public function setFarm(Farm $farm): void
    {
        $this->farm = $farm;
    }

    /**
     * @param \DateTimeImmutable|null $settledAt
     */
    public function setSettledAt(?\DateTimeImmutable $settledAt): void
    {
        $this->settledAt = $settledAt;
    }

    /**
     * @return \DateTimeImmutable|null
     */
    public function getSettledAt(): ?\DateTimeImmutable
    {
        return $this->settledAt;
    }

    /**
     * @return ArrayCollection|Collection
     */
    public function getSlots()
    {
        return $this->slots;
    }

    public function addSlot(Slot $slot): void
    {
        $slot->setOrder($this);
        $this->slots->add($slot);
    }

    public function removeSlot(Slot $slot): void
    {
        $this->slots->removeElement($slot);
    }

    /**
     * @return Slot|null
     */
    public function getChosenSlot(): ?Slot
    {
        return $this->chosenSlot;
    }

    /**
     * @param Slot|null $chosenSlot
     */
    public function setChosenSlot(?Slot $chosenSlot): void
    {
        $this->chosenSlot = $chosenSlot;
    }

    /**
     * @return \DateTimeImmutable|null
     */
    public function getAcceptedAt(): ?\DateTimeImmutable
    {
        return $this->acceptedAt;
    }

    /**
     * @param \DateTimeImmutable|null $acceptedAt
     */
    public function setAcceptedAt(?\DateTimeImmutable $acceptedAt): void
    {
        $this->acceptedAt = $acceptedAt;
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\CartItem;
use App\Entity\Order;
use App\Entity\OrderLine;
use App\Form\AcceptOrderType;
use App\Handler\AcceptOrderHandler;
use App\Handler\UpdateFarmHandler;
use App\HandlerFactory\HandlerFactoryInterface;
use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Workflow\Registry;
use Symfony\Component\Workflow\WorkflowInterface;

/**
 * Class OrderController
 * @package App\Controller
 * @Route("/order")
 */
class OrderController extends AbstractController
{
    /**
     * @return RedirectResponse
     * @Route("/create", name="order_create")
     * @IsGranted("ROLE_CUSTOMER")
     */
    public function create(): RedirectResponse
    {
        $order = new Order();
        $order->setCustomer($this->getUser());

        /** @var CartItem $cartItem */
        foreach ($this->getUser()->getCart() as $cartItem) {
            $line = new OrderLine();
            $line->setOrder($order);
            $line->setQuantity($cartItem->getQuantity());
            $line->setProduct($cartItem->getProduct());
            $line->setPrice($cartItem->getProduct()->getPrice());

            $order->getLines()->add($line);
        }

        $order->setFarm($this->getUser()->getCart()->first()->getProduct()->getFarm());
        $this->getUser()->getCart()->clear();
        $this->getDoctrine()->getManager()->persist($order);
        $this->getDoctrine()->getManager()->flush();
        return $this->redirectToRoute("order_history");
    }

    /**
     * @param OrderRepository $orderRepository
     * @return Response
     * @Route("/manage", name="order_manage")
     * @IsGranted("ROLE_PRODUCER")
     */
    public function manage(OrderRepository $orderRepository): Response
    {
        return $this->render("ui/order/manage.html.twig", [
            "orders" => $orderRepository->findByFarm($this->getUser()->getFarm())
        ]);
    }

    /**
     * @param OrderRepository $orderRepository
     * @return Response
     * @Route("/history", name="order_history")
     * @IsGranted("ROLE_CUSTOMER")
     */
    public function history(OrderRepository $orderRepository): Response
    {
        return $this->render("ui/order/history.html.twig", [
            "orders" => $orderRepository->findByCustomer($this->getUser())
        ]);
    }

    /**
     * @param Order $order
     * @param WorkflowInterface $orderStateMachine
     * @return RedirectResponse
     * @Route("/{id}/cancel", name="order_cancel")
     * @IsGranted("cancel", subject="order")
     */
    public function cancel(Order $order, WorkflowInterface $orderStateMachine): RedirectResponse
    {
        $orderStateMachine->apply($order, 'cancel');
        return $this->redirectToRoute("order_history");
    }

    /**
     * @param Order $order
     * @param WorkflowInterface $orderStateMachine
     * @return RedirectResponse
     * @Route("/{id}/refuse", name="order_refuse")
     * @IsGranted("refuse", subject="order")
     */
    public function refuse(Order $order, WorkflowInterface $orderStateMachine): RedirectResponse
    {
        $orderStateMachine->apply($order, 'refuse');
        return $this->redirectToRoute("order_manage");
    }

    /**
     * @param Order $order
     * @param WorkflowInterface $orderStateMachine
     * @return RedirectResponse
     * @Route("/{id}/settle", name="order_settle")
     * @IsGranted("settle", subject="order")
     */
    public function settle(Order $order, WorkflowInterface $orderStateMachine): RedirectResponse
    {
        $orderStateMachine->apply($order, 'settle');
        return $this->redirectToRoute("order_manage");
    }

    /**
     * @param Request $request
     * @param Order $order
     * @param HandlerFactoryInterface $handlerFactory
     * @return RedirectResponse
     * @Route("/{id}/accept", name="order_accept")
     * @IsGranted("accept", subject="order")
     */
    public function accept(Request $request, Order $order, HandlerFactoryInterface $handlerFactory): Response
    {
        $handler = $handlerFactory->createHandler(AcceptOrderHandler::class);

        if ($handler->handle($request, $order)) {
            return $this->redirectToRoute("order_manage");
        }

        return $this->render("ui/order/accept.html.twig", [
            "form" => $handler->createView()
        ]);
    }
}

templates/ui/order/accept.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-12">
            {{ form_start(form) }}
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h1 class="mb-0">Accepter une commande</h1>
                    <button type="button" class="btn-add btn btn-primary">Ajouter un créneau</button>
                </div>
                <div class="card-body">
                    <div data-prototype="{{ form_row(form.slots.vars.prototype)|e("html_attr") }}" data-index="{{ form.slots|length == 0 ? 0 : form.slots|last.vars.name + 1 }}">
                        {% for slot in form.slots %}
                            {{ form_row(slot) }}
                        {% endfor %}
                    </div>
                </div>
                <div class="card-footer text-right">
                    <button class="btn btn-primary">Valider</button>
                </div>
            </div>
            {{ form_widget(form._token) }}
            {{ form_start(form, { render_rest: false }) }}
        </div>
    </div>
{% endblock %}

templates/ui/order/history.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h1 class="mb-0">Historique de commandes</h1>
                </div>
                <table class="mb-0 table table-striped">
                    <thead>
                    <tr>
                        <th class="text-center">Date de commande</th>
                        <th class="text-center">Nombre de produit</th>
                        <th class="text-center">Total TTC</th>
                        <th class="text-center">Statut</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <td class="text-center">{{ order.createdAt|date("d/m/Y") }}</td>
                            <td class="text-center">{{ order.numberOfProducts }}</td>
                            <td class="text-center">{{ order.totalIncludingTaxes|format_currency('EUR') }}</td>
                            <td class="text-center">
                                {% if order.state == "created" %}
                                    <span class="badge badge-primary">En cours de traitement</span>
                                {% elseif order.state == "canceled" %}
                                    <span class="badge badge-danger">Annuler</span>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if is_granted("cancel", order) %}
                                    <a href="{{ path("order_cancel", { id: order.id }) }}" class="btn btn-outline-warning">Annuler</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/ui/order/manage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h1 class="mb-0">Gestion des commandes</h1>
                </div>
                <table class="mb-0 table table-striped">
                    <thead>
                    <tr>
                        <th class="text-center">Date de commande</th>
                        <th class="text-center">Nombre de produit</th>
                        <th class="text-center">Total TTC</th>
                        <th class="text-center">Statut</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <td class="text-center">{{ order.createdAt|date("d/m/Y") }}</td>
                            <td class="text-center">{{ order.numberOfProducts }}</td>
                            <td class="text-center">{{ order.totalIncludingTaxes|format_currency('EUR') }}</td>
                            <td class="text-center">

                            </td>
                            <td class="text-center">
                                {% if is_granted("accept", order) %}
                                    <a href="{{ path("order_accept", { id: order.id }) }}" class="btn btn-outline-successs">Accepter</a>
                                {% endif %}
                                {% if is_granted("refuse", order) %}
                                    <a href="{{ path("order_refuse", { id: order.id }) }}" class="btn btn-outline-warning">Refuser</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}