src/Entity/Customer.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;

/**
 * Class Customer
 * @package App\Entity
 * @ORM\Entity
 */
class Customer extends User
{
    public const ROLE = "customer";

    /**
     * @ORM\OneToMany(targetEntity="CartItem", mappedBy="customer", cascade={"persist"}, orphanRemoval=true)
     */
    private Collection $cart;

    /**
     * Customer constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->cart = new ArrayCollection();
    }

    public function getRoles(): array
    {
        return ['ROLE_CUSTOMER'];
    }

    /**
     * @return ArrayCollection|Collection
     */
    public function getCart()
    {
        return $this->cart;
    }

    public function addToCart(Product $product): void
    {
        $products = $this->cart->filter(fn (CartItem $cartItem) => $cartItem->getProduct() == $product);

        if ($products->count() === 0) {
            $cartItem = new CartItem();
            $cartItem->setQuantity(1);
            $cartItem->setCustomer($this);
            $cartItem->setProduct($product);
            $this->cart->add($cartItem);
            return;
        }

        $products->first()->increaseQuantity();
    }

    /**
     * @return float
     */
    public function getTotalCartIncludingTaxes(): float
    {
        return array_sum($this->cart->map(fn (CartItem $cartItem) => $cartItem->getPriceIncludingTaxes())->toArray());
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Ramsey\Uuid\UuidInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Product
 * @package App\Entity
 * @ORM\Entity
 * @ORM\EntityListeners({"App\EntityListener\ProductListener"})
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid")
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    private UuidInterface $id;

    /**
     * @ORM\Column
     * @Assert\NotBlank
     */
    private string $name = "";

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private string $description = "";

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\GreaterThanOrEqual(0)
     */
    private int $quantity = 0;

    /**
     * @ORM\ManyToOne(targetEntity="Farm")
     * @ORM\JoinColumn(onDelete="CASCADE", nullable=false)
     */
    private ?Farm $farm = null;

    /**
     * @ORM\Embedded(class="Price")
     * @Assert\Valid
     */
    private Price $price;

    /**
     * @ORM\Embedded(class="Image")
     * @Assert\Valid
     */
    private ?Image $image = null;

    /**
     * @return UuidInterface
     */
    public function getId(): UuidInterface
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * @return int
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    /**
     * @param int $quantity
     */
    public function setQuantity(int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * @return Farm|null
     */
    public function getFarm(): ?Farm
    {
        return $this->farm;
    }

    /**
     * @param Farm|null $farm
     */
    public function setFarm(?Farm $farm): void
    {
        $this->farm = $farm;
    }

    /**
     * @return Price
     */
    public function getPrice(): Price
    {
        return $this->price;
    }

    /**
     * @param Price $price
     */
    public function setPrice(Price $price): void
    {
        $this->price = $price;
    }

    /**
     * @return float
     */
    public function getPriceIncludingTaxes(): float
    {
        return ($this->price->getUnitPrice() * $this->price->getVat()) / 100;
    }

    /**
     * @return Image|null
     */
    public function getImage(): ?Image
    {
        return $this->image;
    }

    /**
     * @param Image|null $image
     */
    public function setImage(?Image $image): void
    {
        $this->image = $image;
    }
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Customer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class CartType
 * @package App\Form
 */
class CartType extends AbstractType
{
    /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add("cart", CollectionType::class, [
            "entry_type" => CartItemType::class
        ]);
    }

    /**
     * @inheritDoc
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefault("data_class", Customer::class);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\CartType;
use App\Handler\AcceptOrderHandler;
use App\Handler\CartHandler;
use App\HandlerFactory\HandlerFactoryInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * Class CartController
 * @package App\Controller
 * @Route("/cart")
 * @IsGRanted("ROLE_CUSTOMER")
 */
class CartController extends AbstractController
{
    /**
     * @param Product $product
     * @return RedirectResponse
     * @Route("/add/{id}", name="cart_add")
     * @IsGranted("add_to_cart", subject="product")
     */
    public function add(Product $product): RedirectResponse
    {
        $this->getUser()->addToCart($product);
        $this->getDoctrine()->getManager()->flush();
        $this->addFlash("success", "Le produit a bien été ajouté à votre panier.");
        return $this->redirectToRoute("farm_show", [
            "slug" => $product->getFarm()->getSlug()
        ]);
    }

    /**
     * @param Request $request
     * @param HandlerFactoryInterface $handlerFactory
     * @return Response
     * @Route("/", name="cart_index")
     */
    public function index(Request $request, HandlerFactoryInterface $handlerFactory): Response
    {
        $handler = $handlerFactory->createHandler(CartHandler::class);

        if ($handler->handle($request, $this->getUser())) {
            return $this->redirectToRoute("cart_index");
        }

        return $this->render("ui/cart/index.html.twig", [
            "form" => $handler->createView()
        ]);
    }
}

templates/ui/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-12">
            {{ form_start(form) }}
            <div class="card">
                <div class="card-header">
                    <h1 class="mb-0">Mon panier</h1>
                </div>
                <table class="mb-0 table table-striped">
                    <thead>
                    <tr>
                        <th class="text-center">Nom du produit</th>
                        <th class="text-center">Prix unitaire</th>
                        <th class="text-center">TVA</th>
                        <th class="text-center">Quantité</th>
                        <th class="text-center">Prix total</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for cartItem in form.cart %}
                        <tr>
                            <td class="text-center">{{ cartItem.vars.data.product.name }}</td>
                            <td class="text-center">{{ (cartItem.vars.data.product.price.unitPrice/100)|format_currency('EUR') }}</td>
                            <td class="text-center">{{ cartItem.vars.data.product.price.vat }}%</td>
                            <td class="text-center">{{ form_widget(cartItem.quantity) }}</td>
                            <td class="text-center">{{ cartItem.vars.data.priceIncludingTaxes|format_currency('EUR') }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="text-right" colspan="4">Total TTC</td>
                            <td class="text-center">{{ app.user.totalCartIncludingTaxes|format_currency('EUR') }}</td>
                        </tr>
                    </tfoot>
                </table>
                <div class="card-footer">
                    <button class="btn btn-block btn-primary">Modifier</button>
                    <a href="{{ path("order_create") }}" class="btn btn-block btn-primary">Passer commande</a>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}